# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
#- archive
- profile
- recent_posts
- category
- friends
#- tag
#- tagcloud

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-66121951-1
tencent_analytics: 53341100
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
